In [30]:
import tensorflow as tf
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split,cross_val_score,KFold
from sklearn.linear_model import LogisticRegression
from tensorflow.keras import Sequential,layers
from datetime import datetime
from sklearn.preprocessing import OneHotEncoder
import random

In [2]:
print(tf.__version__)

1.15.0


In [3]:
filePath='/home/ankit/Documents/ML/ImageInfoExtractor/datasets/Digital_Music_5.json'

In [4]:
df=pd.read_json(filePath, lines=True)

In [5]:
df

reviewerID        asin                 reviewerName helpful  \
0      A3EBHHCZO6V2A4  5555991584         Amaranth "music fan"  [3, 3]   
1       AZPWAXJG9OJXV  5555991584                    bethtexas  [0, 0]   
2      A38IRL0X2T4DPF  5555991584                  bob turnley  [2, 2]   
3      A22IK3I6U76GX0  5555991584                        Calle  [1, 1]   
4      A1AISPOIIHTHXX  5555991584                  Cloud "..."  [1, 1]   
...               ...         ...                          ...     ...   
64701  A1PQ1PESSO8CMO  B00KILDVEI             Ginger Christmas  [0, 0]   
64702  A120RH58WVY4W6  B00KILDVEI  Kelly Dunwell "avid reader"  [0, 0]   
64703  A19VJ2IQLO50G0  B00KILDVEI                      melinda  [0, 1]   
64704   AUDSM2CTLLW1Q  B00KILDVEI           Patrick L. Randall  [0, 0]   
64705  A1GN8UJIZLCA59  B00KILDVEI                     P Magnum  [1, 2]   

                                              reviewText  overall  \
0      It's hard to believe "Memory of Trees" came ou...        5   
1      A clasically-styled and introverted album, Mem...        5   
2      I never thought Enya would reach the sublime h...        5   
3      This is the third review of an irish album I w...        5   
4      Enya, despite being a successful recording art...        4   
...                                                  ...      ...   
64701  I like the reggae sound a lot in this song. I ...        4   
64702  I first heard this on Sirius and had to have i...        5   
64703  I absolutely love this song, it downloaded fin...        5   
64704  Reggae, island beats aren't really my cup of t...        3   
64705  Magic! is a Canadian band that incorporates re...        1   

                            summary  unixReviewTime   reviewTime  
0           Enya's last great album      1158019200  09 12, 2006  
1          Enya at her most elegant       991526400   06 3, 2001  
2                   The best so far      1058140800  07 14, 2003  
3      Ireland produces good music.       957312000   05 3, 2000  
4            4.5; music to dream to      1200528000  01 17, 2008  
...                             ...             ...          ...  
64701                     Cool song      1403568000  06 24, 2014  
64702                    Great Song      1404864000   07 9, 2014  
64703                    Five Stars      1405209600  07 13, 2014  
64704             Well-crafted song      1404864000   07 9, 2014  
64705                Souless Reggae      1405641600  07 18, 2014  

[64706 rows x 9 columns]

In [6]:
subdf=df[["reviewText","summary","overall"]]

In [7]:
subdf.head()

reviewText  \
0  It's hard to believe "Memory of Trees" came ou...   
1  A clasically-styled and introverted album, Mem...   
2  I never thought Enya would reach the sublime h...   
3  This is the third review of an irish album I w...   
4  Enya, despite being a successful recording art...   

                        summary  overall  
0       Enya's last great album        5  
1      Enya at her most elegant        5  
2               The best so far        5  
3  Ireland produces good music.        5  
4        4.5; music to dream to        4

In [8]:
sentences=subdf['reviewText'].values
y=subdf['overall'].values

In [9]:
sentences_train, sentences_test, y_train, y_test=\
train_test_split(sentences,y,test_size=0.20,random_state=62)

In [10]:
vectorizer=CountVectorizer(min_df=0, lowercase=False)
vectorizer.fit(sentences_train)

CountVectorizer(lowercase=False, min_df=0)

In [11]:
X_train=vectorizer.transform(sentences_train)
X_test=vectorizer.transform(sentences_test)
y_train=y_train.reshape(-1,1)
y_test=y_test.reshape(-1,1)

In [12]:
one_hot_encoder=OneHotEncoder(sparse=False)
one_hot_encoder.fit(y_train)
encoded_y_train=one_hot_encoder.transform(y_train)
encoded_y_test=one_hot_encoder.transform(y_test)

In [13]:
print(encoded_y_train)
print(encoded_y_test)

[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 ...
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 ...
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]


In [14]:
#clfBase=LogisticRegression(max_iter=1400)

In [15]:
#clfBase.fit(X_train,encoded_y_train)
#scoreBase=clfBase.score(X_test,encoded_y_test)

ValueError: y should be a 1d array, got an array of shape (51764, 5) instead.

In [ ]:
#print(scoreBase)

In [90]:
clfNN=Sequential()
clfNN.add(layers.Dense(7,input_dim=X_train.shape[1],activation='sigmoid'))
clfNN.add(layers.Dense(8,activation='sigmoid'))
clfNN.add(layers.Dense(5,activation='sigmoid'))

In [91]:
clfNN.compile(loss='categorical_crossentropy',
             optimizer='adam',
             metrics=['accuracy'])

In [92]:
clfNN.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_12 (Dense)             (None, 7)                 948773    
_________________________________________________________________
dense_13 (Dense)             (None, 8)                 64        
_________________________________________________________________
dense_14 (Dense)             (None, 5)                 45        
Total params: 948,882
Trainable params: 948,882
Non-trainable params: 0
_________________________________________________________________


In [93]:
print(X_train.shape)
print(y_train.shape)

(51764, 135538)
(51764, 1)


In [20]:
"""!rm -r ./logs/fit/*
logDirPath='logs/fit/'+datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboardCallback=tf.keras.callbacks.TensorBoard(log_dir=logDirPath,histogram_freq=1)"""

rm: cannot remove './logs/fit/*': No such file or directory


In [ ]:
loss,accuracy=clfNN.evaluate(X_train,encoded_y_train,verbose=False)
print("Training Accuracy: {:.6f} and Loss: {:.7f}".format(accuracy,loss))
loss,accuracy=clfNN.evaluate(X_test,encoded_y_test,verbose=False)
print("Testing  Accuracy: {:.6f} and Loss: {:.7f}".format(accuracy,loss))

In [ ]:
"""
model = Sequential()
model.add(layers.Embedding(input_dim=1049, output_dim=8, input_length=X_train.shape[1]))
model.add(layers.Flatten())
model.add(layers.Dense(5, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
# summarize the model
print(model.summary())
"""

In [94]:
def trainInBatch(model,batch_size,X_train,y_train):
    print("No. of training examples: ",X_train.shape[0])
    numOfBatches=X_train.shape[0]//batch_size
    for idx in range(numOfBatches):
        start=idx*batch_size
        stop=min((idx+1)*batch_size,X_train.shape[0])
        model.fit(X_train[start:stop][:],y_train[start:stop])
                 

In [95]:
def accuracy(model,X,y,batch_size):
    y_pred=np.zeros(y.shape)
    numOfBatches=X.shape[0]//batch_size
    cnt=0
    for idx in range(numOfBatches):
        start=idx*batch_size
        stop=min((idx+1)*batch_size,X.shape[0])
        y_pred[start:stop][:]=model.predict(X[start:stop][:])
    return (y_pred==y).mean()

In [96]:
%time trainInBatch(clfNN,1200,X_train,encoded_y_train)

No. of training examples:  51764
Train on 1200 samples
1200/1200 [==============================] - 1s 855us/sample - loss: 1.8191 - acc: 0.1675
Train on 1200 samples
1200/1200 [==============================] - 1s 814us/sample - loss: 1.6933 - acc: 0.2817
Train on 1200 samples
1200/1200 [==============================] - 1s 802us/sample - loss: 1.6300 - acc: 0.2425
Train on 1200 samples
1200/1200 [==============================] - 1s 787us/sample - loss: 1.5516 - acc: 0.2517
Train on 1200 samples
1200/1200 [==============================] - 1s 799us/sample - loss: 1.5002 - acc: 0.2542
Train on 1200 samples
1200/1200 [==============================] - 1s 810us/sample - loss: 1.4463 - acc: 0.2500
Train on 1200 samples
1200/1200 [==============================] - 1s 859us/sample - loss: 1.3870 - acc: 0.2717
Train on 1200 samples
1200/1200 [==============================] - 1s 821us/sample - loss: 1.3609 - acc: 0.4542
Train on 1200 samples
1200/1200 [==============================] - 1s 8

In [89]:
result1=accuracy(clfNN,X_train,encoded_y_train,1000)
print(result1)

0.011807433737732787


In [97]:
result2=clfNN.evaluate(X_train,encoded_y_train,batch_size=1000)

MemoryError: Unable to allocate 52.3 GiB for an array with shape (51764, 135538) and data type int64

In [59]:
print(X_train.shape,encoded_y_train.shape)

(51764, 135538) (51764, 5)


In [74]:
batch_size=600
start=7000
stop=8000
clfNN.fit(X_train[start:stop][:],encoded_y_train[start:stop][:])
                 
                 

Train on 1000 samples
1000/1000 [==============================] - 1s 786us/sample - loss: 1.1300 - acc: 0.5410
